/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectohernandezgabriel.ventanas;

import java.awt.BorderLayout;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import org.graphstream.ui.view.Viewer;
import proyectohernandezgabriel.Grafo;

/**
 *
 * @author eduar
 */
public class MostrarGrafo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MostrarGrafo.class.getName());
    static Grafo matriz;
    private javax.swing.JButton volver;

    /**
     * Creates new form MostrarGrafo
     *
     * @param matriz
     */
    public MostrarGrafo(Grafo matriz) {
        initComponents();
        MostrarGrafo.matriz = matriz;
        volver = new javax.swing.JButton("Volver");

        volver.setBackground(new java.awt.Color(50, 150, 250));
        volver.setForeground(java.awt.Color.WHITE);

        volver.addActionListener((java.awt.event.ActionEvent evt) -> {
            Principal a = new Principal(matriz);
            a.setVisible(true);
            dispose();
        });

        this.add(volver, java.awt.BorderLayout.NORTH);

        this.revalidate();
        this.repaint();
        this.dibujarGrafo();
        this.setSize(800, 600); 
    this.setLocationRelativeTo(null);

    }

    private void dibujarGrafo() {
        if (matriz == null || matriz.numProteinas == 0) {
            return;
        }

        System.setProperty("org.graphstream.ui", "swing");
        Graph graph = new SingleGraph("RedProteinas");

        String stylesheet
                = "graph { fill-color: #222222; padding: 50px; }"
                + "node { text-size: 18px; text-color: white; size: 25px; text-alignment: at-right; text-offset: 5px, 0px; }"
                + "edge { fill-color: gray; size: 2px; }";
        graph.setAttribute("ui.stylesheet", stylesheet);

        for (int i = 0; i < matriz.numProteinas; i++) {
            if (matriz.proteinas[i] != null) {
                Node n = graph.addNode(matriz.proteinas[i]);
                n.setAttribute("ui.label", matriz.proteinas[i]);
            }
        }
        int edgeId = 0;
        for (int i = 0; i < matriz.numProteinas; i++) {
            for (int j = i; j < matriz.numProteinas; j++) {
                if (matriz.matriz[i][j] > 0) {
                    String p1 = matriz.proteinas[i];
                    String p2 = matriz.proteinas[j];
                    graph.addEdge("e" + edgeId++, p1, p2);
                }
            }
        }

        Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
        viewer.enableAutoLayout();
        ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);

        this.jPanel1.removeAll();
        this.jPanel1.setLayout(new BorderLayout());
        this.jPanel1.add(viewPanel, BorderLayout.CENTER);
        this.jPanel1.revalidate();
        this.jPanel1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MostrarGrafo(matriz).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
