/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectohernandezgabriel.ventanas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import proyectohernandezgabriel.Grafo;
    import org.graphstream.graph.*;
import org.graphstream.graph.implementations.*;
import org.graphstream.ui.view.Viewer;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.swing_viewer.ViewPanel;
import java.awt.BorderLayout;
/**
 *
 * @author Gabriel
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    static Grafo matriz;
    /**
     * Creates new form AgregarProte
     */
    public Principal(Grafo matriz) {
        initComponents();
        matriz = matriz;
    }
    


private void dibujarGrafo() {
    if (matriz == null || matriz.numProteinas == 0) {
        return;
    }

    System.setProperty("org.graphstream.ui", "swing");
    Graph graph = new SingleGraph("RedProteinas");

    String stylesheet = 
        "graph { fill-color: #222222; padding: 50px; }" +
        "node { text-size: 18px; text-color: white; size: 25px; text-alignment: at-right; text-offset: 5px, 0px; }" +
        "edge { fill-color: gray; size: 2px; }";
    graph.setAttribute("ui.stylesheet", stylesheet);

    for (int i = 0; i < matriz.numProteinas; i++) {
        if (matriz.proteinas[i] != null) {
            Node n = graph.addNode(matriz.proteinas[i]);
            n.setAttribute("ui.label", matriz.proteinas[i]);
        }
    }
    int edgeId = 0;
    for (int i = 0; i < matriz.numProteinas; i++) {
        for (int j = i; j < matriz.numProteinas; j++) {
            if (matriz.matriz[i][j] > 0) {
                String p1 = matriz.proteinas[i];
                String p2 = matriz.proteinas[j];
                graph.addEdge("e" + edgeId++, p1, p2);
            }
        }
    }
    
    Viewer viewer = new SwingViewer(graph, Viewer.ThreadingModel.GRAPH_IN_ANOTHER_THREAD);
    viewer.enableAutoLayout();
    ViewPanel viewPanel = (ViewPanel) viewer.addDefaultView(false);

    panelParaGrafo.removeAll(); 
    panelParaGrafo.setLayout(new BorderLayout());
    panelParaGrafo.add(viewPanel, BorderLayout.CENTER);
    panelParaGrafo.revalidate();
    panelParaGrafo.repaint();
}

    
    public void guardarGrafoACSV(File archivo) {
    try (BufferedWriter bw = new BufferedWriter(new FileWriter(archivo))) {
        for (int i = 0; i < matriz.numProteinas; i++) {
            for (int j = i; j < matriz.numProteinas; j++) {
                if (matriz.matriz[i][j] > 0) {
                    String linea = matriz.proteinas[i] + "," + matriz.proteinas[j] + "," + matriz.matriz[i][j];
                    bw.write(linea);
                    bw.newLine();
                }
            }
        }
        javax.swing.JOptionPane.showMessageDialog(null, "Grafo guardado con éxito.");
    } catch (IOException e) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error al escribir el archivo: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        jButton2.setText("jButton1");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jButton3.setText("jButton3");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
    selector.setDialogTitle("Seleccione dónde guardar el CSV");

    javax.swing.filechooser.FileNameExtensionFilter filtro = 
        new javax.swing.filechooser.FileNameExtensionFilter("Archivo CSV (*.csv)", "csv");
    selector.setFileFilter(filtro);

    int resultado = selector.showSaveDialog(this);

    if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
        File archivo = selector.getSelectedFile();
        
        String ruta = archivo.getAbsolutePath();
        if (!ruta.toLowerCase().endsWith(".csv")) {
            archivo = new File(ruta + ".csv");
        }
       
        this.guardarGrafoACSV(archivo);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
    int estado = selector.showOpenDialog(this);

    if (estado == javax.swing.JFileChooser.APPROVE_OPTION) {
        File archivo = selector.getSelectedFile();
        
        Grafo miGrafo = new Grafo();
        
        try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = br.readLine()) != null) {
                String[] partes = linea.split(",");
                
                if (partes.length >= 3) {
                    String p1 = partes[0].trim();
                    String p2 = partes[1].trim();
                    int peso = Integer.parseInt(partes[2].trim());

                    miGrafo.conectar(p1, p2, peso);
                }
            }
            
            // Al terminar de leer, ejecutamos tu DFS
            String resultado = miGrafo.dfs();
            System.out.println(resultado); // O ponlo en un JTextArea
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal(matriz).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
